version: '2'

services:
  db:
    image: postgres:11
    volumes:
      - /home/fesalas/docker/home-monitor/db_data/_data:/var/lib/postgresql/data
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true      
    env_file:
      - db_env
    network_mode: bridge

  # redis:
  #   image: redis:latest
  #   volumes:
  #     - type: bind
  #       source: /etc/localtime
  #       target: /etc/localtime
  #       read_only: true     
  #   expose:
  #     - "6379"
  #   network_mode: bridge

  home-monitor:
    image: home-monitor
    env_file:
      - db_env
      # - django_env
    environment:
      - DJANGO_ENV=dev #dev o prod
    volumes:
      - /home/fesalas/docker/home-monitor/:/code/
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true     
    ports:
      - 8000:8000
    # expose:
    #   - 8000
    depends_on:
      - db
      # - redis
    links:
      - "db"
      # - "redis"
    network_mode: bridge


  nginx:
    image: nginx
    ports:
      - 80:80
     # - 443:443
     # - 127.0.0.1:8001:81
    depends_on:
      - home-monitor
    volumes:
      - /home/fesalas/docker/home-monitor/homemonitor/static:/static
      # - /home/fesalas/docker/home-monitor/media:/media
      # - /home/fsalas/site/ssl:/tmp/ssl      
      - /home/fesalas/docker/home-monitor/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/fesalas/docker/home-monitor/images :/images
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true     
    network_mode: bridge
    links:
      - "home-monitor"

volumes:
  migrate-data: